all:
	echo Making Energy_AddBackSupp.
	(cd AddBackSupp r && make -is clean && make && make -is clean && cd ..)
	echo DONE: TIGRESS_PINARRAYELIM_ADDBACKSUPP.

clean:
	(cd  AddBackSupp && make -is clean && cd ..)
	rm -f *~