all:
	echo making Griffin_CSIARRAY_TTRawDiffCluster
	(cd TTRawDiffCluster r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: Griffin_CSIARRAY_TTRawDiffCluster


clean:
	(cd TTRawDiffCluster && make -is clean && cd ..)
	rm *~