all:
	echo making Tigress_ColorFold
	(cd ColorFold r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_COLORFOLD

	echo making Tigress_EBGORaw
	(cd EBGORaw r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_EBGORAW

	echo making Tigress_ECal
	(cd ECal r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_ECal

	echo making Tigress_ECalLim
	(cd ECalLim r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_ECalLim

	echo making Tigress_ECalRing
	(cd ECalRing r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_ECalRing

	echo making Tigress_ECalRingLim
	(cd ECalRingLim r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_ECalRingLim

	echo making Tigress_ECalRingLimCluster
	(cd ECalRingLimCluster r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_ECalRingLimCluster

	echo making Tigress_ECalRingProj
	(cd ECalRingProj r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_ECalRingProj

	echo making Tigress_ERaw
	(cd ERaw r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_ERaw

	echo making Tigress_ESegRaw
	(cd ESegRaw r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_ESegRaw

	echo making Tigress_GePosFold
	(cd GePosFold r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_GEPOSFOLD

	echo making Tigress_GePosHP
	(cd GePosHP r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_GEPOSHP

	echo making Tigress_RFAddBack
	(cd RFAddBack r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_RFADDBACK

	echo making Tigress_SuppRFAddBack
	(cd SuppRFAddBack r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_SUPPRFADDBACK

	echo making Tigress_SuppRFAddBackPosHP
	(cd SuppRFAddBackPosHP r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_SUPPRFADDBACKPOSHP

	echo making Tigress_TAddBack
	(cd TAddBack r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_TADDBACK

	echo making Tigress_TBGORaw
	(cd TBGORaw r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_TBGORAW

	echo making Tigress_TCal
	(cd TCal r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_TCal

	echo making Tigress_TCalLim
	(cd TCalLim r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_TCalLim

	echo making Tigress_TECal
	(cd TECal r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_TECal

	echo making Tigress_TGeBGO
	(cd TGeBGO r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_TGeBGO

	echo making Tigress_TRaw
	(cd TRaw r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIGRESS_TRaw


clean:
	(cd ECal && make -is clean && cd ..)
	(cd ECalLim && make -is clean && cd ..)
	(cd ESegRaw && make -is clean && cd ..)
	(cd ERaw && make -is clean && cd ..)
	(cd ECalRing && make -is clean && cd ..)
	(cd ECalRingLim && make -is clean && cd ..)
	(cd GePosFold && make -is clean && cd ..)
	(cd GePosHP && make -is clean && cd ..)
	(cd TRaw && make -is clean && cd ..)
	(cd TCal && make -is clean && cd ..)
	(cd TCalLim && make -is clean && cd ..)
	(cd TECal && make -is clean && cd ..)
	(cd TGeBGO && make -is clean && cd ..)
	rm *~