all:
	echo Making AngleBetweenHits_EGated.
	(cd AngleBetweenHits_EGated r && make -is clean && make && make -is clean && cd ..)
	echo DONE: AngleBetweenHits_EGated.
	
	echo Making ECalAB_CsIPIDtr.
	(cd ECalAB_CsIPIDtr r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALAB_CSIPIDTR.
	
	echo Making ECalAB_CsIPIDr.
	(cd ECalAB_CsIPIDr r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALAB_CSIPIDR.
	
	echo Making ECalABSum_CsIPIDr.
	(cd ECalABSum_CsIPIDr r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUM_CSIPIDR.
	
	echo Making ECalABSuppSum_CsIPIDr.
	(cd ECalABSuppSum_CsIPIDr r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPSUM_CSIPIDR.
	
	echo Making ECalABRingSum_CsIPIDr.
	(cd ECalABRingSum_CsIPIDr r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABRINGSUM_CSIPIDR.
	
	echo Making ECalABSuppRingSum_CsIPIDr.
	(cd ECalABSuppRingSum_CsIPIDr r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPRINGSUM_CSIPIDR.
	
	echo Making ECalABSum_CsIEGate_CsIPIDr.
	(cd ECalABSum_CsIEGate_CsIPIDr r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUM_CSIEGATE_CSIPIDR.
	
	echo Making ECalABSuppRingSum_deltaUcut.
	(cd ECalABSuppRingSum_deltaUcut r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPRINGSUM_DELTAUCUT.
	
	echo Making ECalABSuppDSSum.
	(cd ECalABSuppDSSum r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPDSSUM.
	
	echo Making ECalABSuppDSSumEGated.
	(cd ECalABSuppDSSumEGated r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPDSSUMEGATED.
	
	echo Making ECalABSuppSumTree.
	(cd ECalABSuppSumTree r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPSUMTREE.
	
	echo Making deltaU_ECalCut.
	(cd deltaU_ECalCut r && make -is clean && make && make -is clean && cd ..)
	echo DONE: DELTAU_ECALCUT.
	
	echo Making ECalABRing_CsIEGate.
	(cd  ECalABRing_CsIEGate r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABRING_CSIEGATE.
	
	echo Making ECalABRingSum_CsIEGate.
	(cd  ECalABRingSum_CsIEGate r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABRINGSUM_CSIEGATE.
	
	echo Making EE_Plunger.
	(cd  EE_Plunger r && make -is clean && make && make -is clean && cd ..)
	echo DONE: EE_PLUNGER.
	
	echo Making EE_PlungerSum.
	(cd  EE_PlungerSum r && make -is clean && make && make -is clean && cd ..)
	echo DONE: EE_PLUNGERSUM.
	
	echo Making EECal.
	(cd  EECal r && make -is clean && make && make -is clean && cd ..)
	echo DONE: EECAL.
	
	echo Making ECosThetaCalABSuppSum.
	(cd  ECosThetaCalABSuppSum r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum.
	
	echo Making ECosThetaCalABSuppSum_LineCut.
	(cd  ECosThetaCalABSuppSum_LineCut r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum_LineCut.
	
	echo Making ECosThetaCalABSuppSum_LineCutThreshold.
	(cd  ECosThetaCalABSuppSum_LineCutThreshold r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum_LineCutThreshold.
	
	echo Making ECosThetaCalABSuppSum_Rotated.
	(cd  ECosThetaCalABSuppSum_Rotated r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum_Rotated.
	
	echo Making ECosThetaCalABSuppSum_RotatedCosThetaGate.
	(cd  ECosThetaCalABSuppSum_RotatedCosThetaGate r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum_RotatedCosThetaGate.
	
	echo Making ECalABSuppDSReconstructed.
	(cd  ECalABSuppDSReconstructed r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppDSReconstructed.
	
	echo Making ECosThetaCalABSuppSum_Sheared.
	(cd  ECosThetaCalABSuppSum_Sheared r && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum_Sheared.
	
	echo Making FusEvap_ResE.
	(cd  FusEvap_ResE r && make -is clean && make && make -is clean && cd ..)
	echo DONE: FusEvap_ResE.


clean:
	(cd AngleBetweenHits_EGated            && make -is clean && cd ..)
	(cd ECalAB_CsIPIDtr                    && make -is clean && cd ..)
	(cd ECalAB_CsIPIDr                     && make -is clean && cd ..)
	(cd ECalABSum_CsIPIDr                  && make -is clean && cd ..)
	(cd ECalABSuppSum_CsIPIDr              && make -is clean && cd ..)
	(cd ECalABRingSum_CsIPIDr              && make -is clean && cd ..)
	(cd ECalABSuppRingSum_CsIPIDr          && make -is clean && cd ..)
	(cd ECalABSum_CsIEGate_CsIPIDr         && make -is clean && cd ..)
	(cd ECalABSuppRingSum_deltaUcut        && make -is clean && cd ..)
	(cd ECalABSuppDSSum                    && make -is clean && cd ..)
	(cd ECalABSuppDSSumEGated              && make -is clean && cd ..)
	(cd ECalABSuppSumTree                  && make -is clean && cd ..)
	(cd deltaU_ECalCut                     && make -is clean && cd ..)
	(cd ECalABRing_CsIEGate                && make -is clean && cd ..)
	(cd ECalABRingSum_CsIEGate             && make -is clean && cd ..)
	(cd EE_Plunger                         && make -is clean && cd ..)
	(cd EE_PlungerSum                      && make -is clean && cd ..)
	(cd EECal                              && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum              && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum_LineCut      && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum_LineCutThreshold     && make -is clean && cd ..)
	(cd Making ECosThetaCalABSuppSum_Rotated       && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum_RotatedCosThetaGate  && make -is clean && cd ..)
	(cd ECalABSuppDSReconstructed  && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum_Sheared  && make -is clean && cd ..)
	(cd FusEvap_ResE  && make -is clean && cd ..)

	rm -f *~
